apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dante-id
  namespace: dante
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - app.dante.id
        - api.dante.id
      secretName: dante-id-tls
  rules:
    - host: app.dante.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dante-id
                port:
                  number: 80
    - host: api.dante.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dante-id
                port:
                  number: 80
