apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: queue-dashboard-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - tasks-prod.dante.id
      secretName: tasks-prod-tls
  rules:
    - host: tasks-prod.dante.id
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: queue-dashboard
                port:
                  number: 3000
