apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - neo/pvc.yaml
  - neo/configmap.yaml
  - neo/deployment.yaml
  - neo/service.yaml
  - mu/pvc.yaml
  - mu/configmap.yaml
  - mu/deployment.yaml
  - mu/service.yaml
  - beta/pvc.yaml
  - beta/configmap.yaml
  - beta/deployment.yaml
  - beta/service.yaml
